# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reachUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_name', models.CharField(max_length=50, null=True)),
                ('Contact_number', models.IntegerField(null=True)),
                ('Contact_address', models.TextField(null=True)),
                ('Contact_email_address', models.TextField(null=True)),
                ('Contact_location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
