# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
        migrations.AlterField(
            model_name='reachus',
            name='Contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
