# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='keProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_title', models.CharField(max_length=100)),
                ('prof_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='postInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('post_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_pub_date', models.DateTimeField(blank=True, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reachUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=50, null=True)),
                ('cont_number', models.IntegerField(null=True)),
                ('cont_address', models.TextField(null=True)),
                ('cont_location', models.TextField(default='Mombasa')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=50)),
                ('pro_descriiption', models.TextField()),
            ],
        ),
    ]
