# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Proverbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proverb_creation_date', models.DateField(default=django.utils.timezone.now)),
                ('Proverb_publish_date', models.DateField()),
                ('Proverb', models.TextField()),
                ('Proverb_translation', models.TextField(blank=True, null=True)),
                ('Proverb_meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_title', models.TextField()),
                ('Review_customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Review_narration', models.TextField()),
                ('Review_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='keProfile',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='post_author',
        ),
        migrations.RenameField(
            model_name='reachus',
            old_name='cont_address',
            new_name='Contact_address',
        ),
        migrations.RenameField(
            model_name='reachus',
            old_name='cont_email_address',
            new_name='Contact_email_address',
        ),
        migrations.RenameField(
            model_name='reachus',
            old_name='con_name',
            new_name='Contact_name',
        ),
        migrations.RenameField(
            model_name='reachus',
            old_name='cont_number',
            new_name='Contact_number',
        ),
        migrations.RemoveField(
            model_name='reachus',
            name='cont_location',
        ),
        migrations.AddField(
            model_name='reachus',
            name='Contact_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='postInfo',
        ),
    ]
