# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160714_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Review_title',
            field=models.CharField(max_length=50),
        ),
    ]
