# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160718_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(null=True, upload_to='home'),
        ),
    ]
