# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160720_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reachUs',
        ),
    ]
