# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_reachus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='picture',
            new_name='Picture',
        ),
        migrations.AddField(
            model_name='images',
            name='Picture_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
