# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kenyaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keTitle', models.CharField(max_length=20)),
                ('keInfo', models.TextField()),
                ('keImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
