# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya', '0002_auto_20160708_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenyainfo',
            name='keImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
