# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenya', '0004_auto_20160714_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kenyainfo',
            old_name='keInfo',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='kenyainfo',
            old_name='keImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='kenyainfo',
            old_name='keTitle',
            new_name='Title',
        ),
    ]
