# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya', '0005_auto_20160714_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenyainfo',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
