# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detailedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=50)),
                ('serviceDescription', models.TextField()),
                ('serviceImage', models.ImageField(null=True, upload_to='')),
                ('serviceCreateDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('serviceToBeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('serviceLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=50)),
                ('productDescription', models.TextField()),
                ('productImage', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
