# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedservice',
            name='serviceType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.service'),
        ),
    ]
