# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_detailedservice_servicetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceCreateDate',
            new_name='service_CreateDate',
        ),
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceDescription',
            new_name='service_Description',
        ),
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceLocation',
            new_name='service_Location',
        ),
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceTitle',
            new_name='service_Title',
        ),
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceToBeDate',
            new_name='service_ToBeDate',
        ),
        migrations.RenameField(
            model_name='detailedservice',
            old_name='serviceType',
            new_name='service_Type',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='productDescription',
            new_name='product_Description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='productTitle',
            new_name='product_Title',
        ),
        migrations.RemoveField(
            model_name='detailedservice',
            name='serviceImage',
        ),
        migrations.RemoveField(
            model_name='service',
            name='productImage',
        ),
        migrations.AddField(
            model_name='detailedservice',
            name='service_Image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
        migrations.AddField(
            model_name='service',
            name='product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
