# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160714_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedservice',
            name='service_CreateDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='detailedservice',
            name='service_Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailedservice',
            name='service_ToBeDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
