# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160824_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product_Number',
            field=models.IntegerField(null=True),
        ),
    ]
