# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_service_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='product_Number',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
